dineinhall/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, IntegerField, SubmitField, SelectField, DecimalField
from wtforms.validators import Optional, NumberRange


# form to search for food items on advanced search page
class SearchForm(FlaskForm):
    iv = BooleanField('International Village')
    steast = BooleanField('Stetson East')
    stwest = BooleanField('Stetson West')
    meal = SelectField('Meal', choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')])
    vegetarian = BooleanField('Vegetarian')
    vegan = BooleanField('Vegan')
    balanced = BooleanField('Balanced')
    foodName = StringField('Food Name', validators=[Optional()])
    calories = IntegerField('Calories', validators=[Optional(), NumberRange(min=0)])
    protein = IntegerField('Protein', validators=[Optional(), NumberRange(min=0)])
    fat = IntegerField('Fat', validators=[Optional(), NumberRange(min=0)])
    carbs = IntegerField('Carbs', validators=[Optional(), NumberRange(min=0)])
    rating = DecimalField('Rating', validators=[Optional(), NumberRange(min=1, max=5)])
    submit = SubmitField('Search')

dineinhall/main/routes.py
from datetime import datetime
from flask import render_template, Blueprint, redirect, url_for, flash
from pytz import timezone
from sqlalchemy import create_engine

from .forms import SearchForm
from dineinhall.config import Config

main = Blueprint('main', __name__)

# allows us to recreate SQL query statements in Python
engine = create_engine(Config.SQLALCHEMY_DATABASE_URI)


# routes the user to the home page
@main.route("/")
def home():
    return render_template('main.html')


# routes the user to the menu page with the default location being IV
@main.route("/menu")
def menu():
    return redirect(url_for('main.filteredLocations', loc='IV'))


# routes the user to the menu page with the given location tag
@main.route("/menu/<loc>")
def filteredLocations(loc):
    with engine.connect() as con:
        # find all the foods for the current date from the given location
        rs = con.execute('select distinct * '
                         'from menu join food_on_menu using (menu_id) '
                         ' join food using (food_id) where menu_date '
                         f"= curdate() and location like '{loc}'")

    foods = list(rs)
    # if there is no food available that day, the location is closed
    closed = len(foods) == 0
    locations = {'Stwest': False, 'IV': False, 'Steast': False}
    # sets the used location to be true in order to display location name
    locations[loc] = True

    return render_template('menu.html', allFoods=foods, stwest=locations['Stwest'], iv=locations['IV'], steast=locations['Steast'], closed=closed, title=loc)


# the advanced search page for querying foods using specific attributes
@main.route("/AdvancedSearch", methods=['GET', 'POST'])
def search():
    # advanced search form object
    form = SearchForm()
    # if form is submitted successfully
    if form.validate_on_submit():
        # boolean values for location
        iv = form.iv.data
        steast = form.steast.data
        stwest = form.stwest.data
        # numeric values for nutrients
        calories = form.calories.data
        protein = form.protein.data
        fat = form.fat.data
        carbs = form.carbs.data
        # breakfast, lunch, or dinner
        meal = form.meal.data
        # split food name into a list of strings
        foodName = form.foodName.data.split()
        # rating on a 5pt scale
        rating = form.rating.data
        # boolean values for food properties
        vegetarian = form.vegetarian.data
        vegan = form.vegan.data
        balanced = form.balanced.data
        foodNameQuery = "true "
        # for each word in the searched food find a food item that contains the given word
        for word in foodName:
            foodNameQuery += f"and food_name like '%%{word}%%' "
        # if user does not choose any location, shows all by default
        if not(iv or steast or stwest):
            iv, steast, stwest = True, True, True
        # foods from dining hall locations
        iv = "location like 'IV'" if iv else False
        steast = "location like 'Steast'" if steast else False
        stwest = "location like 'Stwest'" if stwest else False
        # foods less or equal to than the given calories
        calories = f"calories <= {calories}" if calories is not None else True
        # foods more than or equal to the given protein
        protein = f"protein >= {protein}" if protein is not None else True
        # foods less than or equal to the given fat
        fat = f"total_fat <= {fat}" if fat is not None else True
        # foods less than or equal to the given carbs
        carbs = f"total_carbs <= {carbs}" if carbs is not None else True
        # foods with ratings greater than or equal to the given rating (including not yet rated)
        rating = f"(ratings >= {rating} or isnull(ratings))" if rating is not None else True
        vegetarian = "vegetarian = True" if vegetarian else True
        vegan = "vegan = True" if vegan else True
        balanced = "balanced = True" if balanced else True
        # set a timezone to avoid the inconsistent timezone of the Heroku server
        curdate = datetime.now(timezone('US/Eastern'))  # EST timezone
        curdate = curdate.strftime("%Y-%m-%d")
        with engine.connect() as con:
            # main query searching for food items with all the specified attributes
            # if a value is not given deafault it to True so the query skips over it
            foods = con.execute("select distinct * "
                                f"from menu join food_on_menu using (menu_id) "
                                f"join food using (food_id) "
                                f"left join (select food_id, round(avg(stars), 2) ratings from rating group by food_id) food_ratings "
                                f"using (food_id) where menu_date = '{curdate}' "
                                f"and ({iv} or {steast} or {stwest}) "
                                f"and {calories} and {protein} and {fat} and {carbs} "
                                f"and meal_type like '{meal}' "
                                f"and {rating} "
                                f"and {foodNameQuery} "
                                f"and {vegetarian} and {vegan} and {balanced} "
                                f"order by location desc, meal_type asc, calories desc, food_name desc")
        foods = list(foods)
        size = len(foods)
        # if there are no foods for the given specifications
        if size == 0:
            flash('No items matched with your query', 'danger')
        else:
            flash(f'Found {size} matching results!', 'success')
    else:
        foods = []
        # default message which pops up once going to the page
        flash('Start Searching!', 'success')
    return render_template('advancedSearch.html', title='Advanced Search', form=form, allFoods=foods)

dineinhall/reviews/routes.py
from datetime import datetime
from flask import render_template, Blueprint, redirect, url_for, flash
from flask_login import current_user, login_required
from pytz import timezone
from sqlalchemy import create_engine

from .forms import ReviewForm
from dineinhall import db
from dineinhall.config import Config
from dineinhall.models import Rating

review = Blueprint('review', __name__)

# allows us to recreate SQL query statements in Python
engine = create_engine(Config.SQLALCHEMY_DATABASE_URI)


# page where user creates a new review (must be logged in)
@review.route("/newReview/<food_id>", methods=['GET', 'POST'])
@login_required
def newReview(food_id):
    # food review form object
    form = ReviewForm()
    if form.validate_on_submit():
        user_id = current_user.user_id
        stars = form.stars.data
        description = form.description.data.strip()
        # description is None type if not input
        description = description if description else None
        timestamp = datetime.now(timezone('US/Eastern'))  # EST timezone
        timestamp = timestamp.strftime("%Y-%m-%d %H:%M:%S")
        rating = Rating(user_id=user_id, food_id=food_id, stars=stars, description=description, timestamp=timestamp)
        try:
            db.session.add(rating)
            db.session.commit()
            flash('Succesfully reviewed', 'success')
        except Exception:
            flash('Error in submitting review', 'danger')
    return render_template('newRating.html', title='New Review', form=form)


# displays the reviews and rating for every food that has been reviewed/rated
@review.route("/reviews")
def reviews():
    return redirect(url_for('review.foodReview', food_id=-1))


# displays the reviews and rating for the specified food
@review.route("/reviews/<food_id>")
def foodReview(food_id):
    if int(food_id) == -1:
        food_id = True
    else:
        food_id = f'food_id = {food_id}'
    with engine.connect() as con:
        # all the reviews for the given food id where the description exists
        reviews = con.execute("select * "
                              f"from food join rating using (food_id) "
                              f"join user using (user_id) "
                              f"where not isnull(rating.description) and {food_id} "
                              f"order by timestamp desc")
    reviews = list(reviews)
    size = len(reviews)

    # if there are no reviews for the given food id
    if size == 0:
        flash('No reviews found', 'danger')
    else:
        flash(f'Found {size} reviews!', 'success')
    return render_template('reviews.html', title='Ratings', reviews=reviews)

dineinhall/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from sqlalchemy import create_engine

from dineinhall import db, bcrypt
from dineinhall.config import Config
from dineinhall.models import User
from dineinhall.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from dineinhall.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

# allows us to recreate SQL query statements in Python
engine = create_engine(Config.SQLALCHEMY_DATABASE_URI)


# register page where the new users can register for an account given the right validated credentials
@users.route("/register", methods=['GET', 'POST'])
def register():
    # if user is already logged in redirect user to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    # user registration form object
    form = RegistrationForm()
    # checks if the user put in valid informaton to register for an account
    if form.validate_on_submit():
        # hashes password to store in database
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # get user object
        user = User(user_name=form.username.data, email=form.email.data, password=hashed_password)
        # add user to database
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


# login page where returning users can log back into their account
@users.route("/login", methods=['GET', 'POST'])
def login():
    # if user is already logged in redirect user to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    # user login form object
    form = LoginForm()
    # checks if the user put in valid informaton to log into their account
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # checks if decrypted password matches the password stored for the user in the database
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            # redirect user to the page they were previously on else redirect to the home page
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


# allows users to log out of their account, if already logged in
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


# allows users to see their personal account page with profile picture (must be logged in)
# users can also change their username and email on their account page
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    # user update account form object
    form = UpdateAccountForm()
    # checks if the user put in valid informaton to update into their account
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.profile_pic = picture_file
        current_user.user_name = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.user_name
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/default.jpg')
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


# shows all reviews/ratings for the specified user
@users.route("/user/<string:username>")
def user_reviews(username):
    with engine.connect() as con:
        # filters out the review from just the given username
        # and a description exists
        reviews = con.execute("select * "
                              f"from food join rating using (food_id) "
                              f"join user using (user_id) "
                              f"where not isnull(description) and user_name='{username}' "
                              f"order by timestamp desc")
    reviews = list(reviews)
    size = len(reviews)

    # determining message displayed after a search
    if size == 0:
        flash('No reviews from this user', 'danger')
    else:
        flash(f'Found {size} reviews!', 'success')
    return render_template('reviews.html', title='Ratings', reviews=reviews)


# allows users to request a password reset
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    # if user is already logged in redirect user to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    # user request password reset form object
    form = RequestResetForm()
    # checks if the user entered in a valid existing email that's linked to an account to reset their password
    if form.validate_on_submit():
        # get user object
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


# allows users to reset their password
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    # if user is already logged in redirect user to home page
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    # if there is not a user with the given token
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    # user reset password form object
    form = ResetPasswordForm()
    # if the form has been submitted succesfully
    if form.validate_on_submit():
        # hash the users password to store in database
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

dineinhall/templates/advancedSearch.html
{% extends "layout.html" %}
{% block content %}
  <h1>Advanced Search</h1>
  {% for food in allFoods %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <a href="{{ url_for('review.foodReview', food_id=food.food_id) }}">
            <b><u>{{ food.food_name }}</u></b>
          </a>
          <!-- Dining Hall Location -->
          {% if food.location == 'Steast' %}
            <b>(SE)</b>
          {% elif food.location == 'Stwest' %}
            <b>(SW)</b>
          {% else %}
            <b>({{food.location}})</b>
          {% endif %}
          <span style="float:right">
            <a href="{{ url_for('review.newReview', food_id=food.food_id) }}" class="btn btn-primary" role="button">
              New Review
            </a>
          </span>
        </br>
        <i>
          <!-- Drawing food rating stars using a for loop -->
          {% set starCount = food.ratings %}
          {% if starCount != None %}
            {% set starCount = food.ratings|round|int %}
            {% for num in [1, 2, 3, 4, 5] %}
              {% if num <= starCount %}
                ★
              {% else %}
                ☆
              {% endif %}
            {% endfor %}
            ({{ food.ratings }})
            {% else %}
              Not Yet Rated
            {% endif %}
        </i>
        <br>
        {{ "Calories: "}}
        {{ food.calories }} |
        {{ "Protein: "}}
        {{ food.protein }} |
        {{ "Carbs: "}}
        {{ food.total_carbs }} |
        {{ "Fat: "}}
        {{ food.total_fat }} |
        {{ "Portions: "}}
        {{ food.serving }}
      </div>
    </div>
    </article>
  {% endfor %}
{% endblock content %}
{% block sidebar %}
  <div class="col-md-4">
    <div class="content-section">
      <h3>Search</h3>
      <p class='text-muted'>Choose your nutritional preferences.
        <ul class="list-group">
          <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
              <legend class="border-bottom mb-4"></legend>
              <div class="form-group">
                {{ form.foodName.label(class="form-control-label") }}
                {% if form.foodName.errors %}
                  {{ form.foodName(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.foodName.errors %}
                      <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                {% else %}
                  {{ form.foodName(class="form-control form-control") }}
                {% endif %}
              </div>
              <div class="form-check">
                {{ form.iv(class="form-check-input") }}
                {{ form.iv.label(class="form-check-label") }}
              </div>
              <div class="form-check">
                {{ form.steast(class="form-check-input") }}
                {{ form.steast.label(class="form-check-label") }}
              </div>
              <div class="form-check">
                {{ form.stwest(class="form-check-input") }}
                {{ form.stwest.label(class="form-check-label") }}
              </div>
              <br>
              <div class="form-group">
                {{ form.meal.label(class="form-control-label") }}
                {{ form.meal(class="form-control form-control") }}
              </div>
              <div class="form-check">
                {{ form.vegetarian(class="form-check-input") }}
                {{ form.vegetarian.label(class="form-check-label") }}
              </div>
              <div class="form-check">
                {{ form.vegan(class="form-check-input") }}
                {{ form.vegan.label(class="form-check-label") }}
              </div>
              <div class="form-check">
                {{ form.balanced(class="form-check-input") }}
                {{ form.balanced.label(class="form-check-label") }}
              </div>
              <br>
              <div class="form-group">
                {{ form.calories.label(class="form-control-label") }} <i><small>(max.)</small></i>
                {% if form.calories.errors %}
                  {{ form.calories(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.calories.errors %}
                      <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                {% else %}
                  {{ form.calories(class="form-control form-control") }}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.protein.label(class="form-control-label") }} <i><small>(min.)</small></i>
                {% if form.protein.errors %}
                  {{ form.protein(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.protein.errors %}
                      <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                {% else %}
                  {{ form.protein(class="form-control form-control") }}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.fat.label(class="form-control-label") }} <i><small>(max.)</small></i>
                {% if form.fat.errors %}
                  {{ form.fat(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.fat.errors %}
                      <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                {% else %}
                  {{ form.fat(class="form-control form-control") }}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.carbs.label(class="form-control-label") }} <i><small>(max.)</small></i>
                {% if form.carbs.errors %}
                  {{ form.carbs(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.carbs.errors %}
                      <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                {% else %}
                  {{ form.carbs(class="form-control form-control") }}
                {% endif %}
              </div>
              <div class="form-group">
                {{ form.rating.label(class="form-control-label") }} <i><small>(min.)</small></i>
                {% if form.rating.errors %}
                  {{ form.rating(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                    {% for error in form.rating.errors %}
                      <span>{{ error }}</span>
                    {% endfor %}
                  </div>
                {% else %}
                  {{ form.rating(class="form-control form-control") }}
                {% endif %}
              </div>
            </fieldset>
            <div class="form-group">
              {{ form.submit(class="btn btn-outline-info") }}
            </div>
          </form>
        </ul>
      </p>
    </div>
  </div>
{% endblock %}

dineinhall/templates/layout.html
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css')}}">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  {% if title %}
    <title>DineInHall - {{ title }}</title>
  {% else %}
    <title>DineInHall</title>
  {% endif %}
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a href="{{ url_for('main.home') }}">
          <img class ='img-responsive mr-3' src="https://i.imgur.com/nEbjT7b.png" id="logo" />
        </a>
        <a class="navbar-brand" href="/">DineInHall</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('main.menu') }}">Menu</a>
            <a class="nav-item nav-link" href="{{ url_for('main.search') }}">Advanced Search</a>
            <a class="nav-item nav-link" href="{{ url_for('review.reviews') }}">Reviews</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages%}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
      {% block sidebar %}{% endblock %}
    </div>
  </main>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

dineinhall/templates/login.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Log In</legend>
        <!-- Email Field -->
        <div class="form-group">
          {{ form.email.label(class="form-control-label") }}
          {% if form.email.errors %}
            {{ form.email(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <!-- Password Field -->
        <div class="form-group">
          {{ form.password.label(class="form-control-label") }}
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password(class="form-control form-control-lg") }}
          {% endif %}
        </div>
        <!-- Remember Me Option -->
        <div class="form-check">
          {{ form.remember(class="form-check-input") }}
          {{ form.remember.label(class="form-check-label") }}
        </div>
      </fieldset>
      <!-- Submit Button -->
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
        <small class="text-muted ml-2">
          <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
        </small>
      </div>
    </form>
  </div>
  <div class="border-top pt-3">
    <small class="text-muted">
      Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
  </div>
{% endblock content %}

dineinhall/templates/reviews.html
{% extends "layout.html" %}
{% block content %}
  <h1>Reviews</h1>
  <!-- Reviews -->
  {% for review in reviews %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <!-- profile pic -->
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/default.jpg') }}">
          <!-- Username -->
          <a class="mr-2" href="{{ url_for('users.user_reviews', username=review.user_name) }}">{{ review.user_name }}</a>
          <!-- Timestamp -->
          <small class="text-muted">{{ review.timestamp.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2>
          <!-- Food Name -->
          <a class="article-title" href="{{ url_for('review.foodReview', food_id=review.food_id) }}">
            {{ review.food_name }}
          </a>
          <!-- Generate Stars for Rating -->
          <span style="float:right">
            {% set starCount = review.stars %}
            {% for num in [1, 2, 3, 4, 5] %}
              {% if num <= starCount %}
                ★
              {% else %}
                ☆
              {% endif %}
            {% endfor %}
          </span>
        </h2>
        <p class="article-content">{{ review.description }}</p>
      </div>
    </article>
  {% endfor %}
{% endblock content %}